version: "3.9"
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python main.py
    ports:
      - '8000:8000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"